# Spring application configuration
spring.application.name=TalentHub

# PostgreSQL database configuration template (uncomment and edit for your setup)
 spring.datasource.url=jdbc:postgresql://localhost:5432/talenthub_db
 spring.datasource.username=sa
 spring.datasource.password=123456
 spring.datasource.driverClassName=org.postgresql.Driver

# Hibernate/JPA configuration
 spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
 spring.jpa.hibernate.ddl-auto=update

# Logging configuration
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
