# Spring application configuration
spring.application.name=TalentHub

# PostgreSQL database configuration template (uncomment and edit for your setup)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=TalentHubDB;encrypt=true;trustServerCertificate=true
 spring.datasource.username=sa
 spring.datasource.password=123456
 spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate/JPA configuration
 spring.jpa.hibernate.ddl-auto=update

# Logging configuration
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
